export const PARAMS = {
  INTENT: "intent",
  ID: "id",
  EMAIL: "email",
  MESSAGE: "message",
  NAMESPACE: "namespace",
  QUERY: "query",
  NAME: "name",
  SOURCE: "source",
  URL: "url",
  URLS: "urls",
  FILE: "file",
  COLLECTION_NAME: "collectionName",
  COLLECTION_IDS: "collectionIds",
};
