export const PARAMS = {
  COLLECTION_IDS: "collectionIds",
  COLLECTION_NAME: "collectionName",
  EMAIL: "email",
  ERROR: "error",
  FILE: "file",
  ID: "id",
  INTENT: "intent",
  MESSAGE: "message",
  NAME: "name",
  NAMESPACE: "namespace",
  QUERY: "query",
  SOURCE: "source",
  URL: "url",
  URLS: "urls",
};
